FROM node:20-alpine

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json
COPY ./turbo.json ./turbo.json
COPY ./apps/web ./apps/web

RUN npm install
RUN npm run db:migrate
RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start:web"]
